esphome:
  name: warmwasserpumpe
  friendly_name: WarmWasserPumpe
esp32:
  board: esp32dev
  framework:
    type: arduino
# Enable logging
logger:
# Enable Home Assistant API
api:
  encryption:
    key: !secret ota_key
ota:
  password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ssid 
    password: !secret fallback_password
web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
i2c:
  sda: 17
  scl: 16
  scan: true
  id: bus_a
display:
  - platform: lcd_pcf8574
    id: lcd_display
    i2c_id: bus_a
    dimensions: 20x4 
    address: 0x27       
    lambda: |-
      it.print(0,0,"WarmWasser");
      it.printf(0,1,"Gas  :%.0f\337C",id(temp_1_sensor).state);
      it.print(0,2,"Pumpe:");
      if (id(pump_on).state){
        it.print(6,2,"AN");
      }
      else {
        it.print(6,2,"AUS");
      }
      it.printf(0,3,"Solar:%.0f\337C",id(temp_0_sensor).state);
      it.print(11,0,"Pruefung:");
      it.printf(11,1,"%.0f",id(automatik).state);
      it.print(11,2,"Modus:");
      if (id(switch_mode).state){
        it.print(11,3,"Automatik");
      }
      else{
        it.print(11,3,"Manuell");
      }
      it.print(10,0,"|");
      it.print(10,1,"|");
      it.print(10,2,"|");
      it.print(10,3,"|");
output:
  # Relais der Pumpe
  - platform: gpio
    pin: 
      number: 23
    id: 'relais_pump'
switch:
  # Pumpe an/aus
  - platform: template
    name: "Pumpe manuell"
    id: 'switch_pump'
    optimistic: true
  # Modus 
  - platform: template 
    name: "Modus"
    id: 'switch_mode'
    optimistic: true
  # Restart node
  - platform: restart
    name: "Warmwasserpumpe Restart"
      
binary_sensor:
  # Hardware Taster Pumpe an/aus
  - platform: gpio
    pin:
      number: 19
      mode:
        input: true
        pulldown: true
    name: 'button_pump'
    id: 'button_pump'
    on_release:
      then:
        - switch.toggle: switch_pump
  # Hardware Taster Modus
  - platform: gpio
    pin:
      number: 27
      mode:
        input: true
        pulldown: true
    name: 'button_mode'
    id: 'button_mode'
    on_release:
      then:
        - switch.toggle: switch_mode
dallas:
  # 1-Wire Bus für Dallas Temperatur Sensoren
  - pin: 
      number: 25
      mode: 
        input: true
        pullup: true 
    id: temp_bus
    update_interval: 10s
    
sensor:
  # Temperatursensor Tank unten (Solar)
  - platform: dallas
    dallas_id: temp_bus
    id: temp_0_sensor
    address: 0x0cd534ee0264ff28
    name: "Temperatur Wassertank Solar"
  # Temperatursensor Tank oben (Gas)
  - platform: dallas
    dallas_id: temp_bus
    id: temp_1_sensor
    address: 0x4069d99d1e64ff28
    name: "Temperatur Wassertank Gas"
  # Plausibilitätsprüfung für den Automatik-Modus
  - platform: template
    name: "Plausibilitätsprüfung"
    id: 'automatik'
    update_interval: 10s
    lambda: |-
      if (int(id(temp_0_sensor).state) > (int(id(temp_1_sensor).state)+1)) {
        return true;
      } else {
        return false;
      }
  # Logiksensor zum Schalten der Pumpe
  - platform: template
    name: "Pumpe schalten"
    id: 'pump_on'
    update_interval: 1s
    lambda: |-
      if((id(automatik).state && id(switch_mode).state) || (id(switch_pump).state && !id(switch_mode).state))
      {
        id(relais_pump).turn_on();
        return true;
      } else {
        id(relais_pump).turn_off();
        return false;
      }
